import crypto from 'node:crypto';
import path from 'node:path';
import fs from 'node:fs';
import { layout, esc } from './views.js';
import { orderFile, mimeFor } from './files.js';
import { printDescription } from '../public/print-plan.js';
import { transition } from './machine.js';
import { savePartner, assignPurchase, handoverPurchase } from './partners.js';
import { hashPassword } from './auth.js';

const field = (name, label, value = '', type = 'text') => `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" required ${type === 'number' ? 'step="any"' : 'maxlength="200"'}></div>`;
const button = (id, action, text, extra = '') => `${extra && ['reject','problem'].includes(action) ? '<details class="operation-issue"><summary class="rowlink">' + text + '</summary>' : ''}<form method="POST" action="/partner/purchases/${encodeURIComponent(id)}/${action}">${extra}<button class="btn loud" type="submit">${text}</button></form>${extra && ['reject','problem'].includes(action) ? '</details>' : ''}`;

export function installPartnerRoutes(app, { loadDb, saveDb, requireRole, siteOrigin, uploadsDir, notifyState, qualifyForOrder }) {
  app.use(['/partner','/rider','/admin/partners','/admin/delivery'], (_req,res,next) => { res.set('Cache-Control','private, no-store'); res.set('X-Robots-Tag','noindex, nofollow'); next(); });
  const mutate = (role, back, fn) => [siteOrigin, requireRole(role), (req,res) => { try { const db = loadDb(); fn(db,req,res); } catch(error) { res.status(400).send(layout({user:req.user,title:'Please check',body:`<div class="page-heading"><p class="eyebrow">ONE QUICK CHECK</p><h1>Let’s get this <em>right.</em></h1></div><div class="card"><p role="alert">${esc(error.message)}</p><a class="btn loud" href="${back}">Back to orders →</a></div>`})); } }];
  app.get('/admin/partners', requireRole('admin'), (req,res) => {
    const db = loadDb(), shop = (db.partners || []).find(s => s.id === req.query.edit) || {};
    const staff = db.users.filter(u => u.role === 'partner');
    const check = (name,label) => `<label class="pick"><input type="checkbox" name="${name}" ${shop[name] ? 'checked' : ''}>${label}</label>`;
    const rows = (db.partners || []).map(s => `<article class="card operation-card"><h2>${esc(s.name)}</h2><p>${esc(s.address)} · ${s.active ? 'Active' : 'Paused'}</p><p>${s.radiusKm} km · ${s.batchCapacity} orders / batch</p><a class="rowlink" href="/admin/partners?edit=${s.id}">Edit shop →</a></article>`).join('');
    res.send(layout({user:req.user,title:'Partner shops',active:'/admin/partners',body:`<div class="page-heading"><p class="eyebrow">THE LOCAL NETWORK</p><h1>Partner <em>shops.</em></h1><p>Create staff access, enter the shop’s capabilities and service area, then activate it when pickup and rider coverage are ready.</p></div><div class="grid c2"><section class="card operation-card"><h2>${shop.id ? 'Edit' : 'Onboard'} shop</h2><form method="POST" action="/admin/partners"><input type="hidden" name="id" value="${esc(shop.id || '')}">${field('name','Shop name',shop.name)}${field('address','Pickup address',shop.address)}<div class="field"><label for="zone">Area</label><select id="zone" name="zone">${['vapi','daman','sarigam','bhilad'].map(z=>`<option ${shop.zone === z ? 'selected' : ''}>${z}</option>`).join('')}</select></div><div class="grid c2">${field('lat','Latitude',shop.lat ?? 20.389722,'number')}${field('lng','Longitude',shop.lng ?? 72.889945,'number')}${field('radiusKm','Delivery radius (km)',shop.radiusKm ?? 5,'number')}${field('batchCapacity','Orders per batch',shop.batchCapacity ?? 30,'number')}${field('bwRate','B&W settlement / side (₹)',shop.bwRate ?? 1,'number')}${field('colorRate','Colour settlement / side (₹)',shop.colorRate ?? 3,'number')}</div><div class="field"><label for="staffId">Shop staff account</label><select id="staffId" name="staffId" required><option value="">Choose an account</option>${staff.map(u=>`<option value="${esc(u.id)}" ${shop.staffId === u.id ? 'selected' : ''}>${esc(u.name)} · ${esc(u.email)}</option>`).join('')}</select></div>${check('active','Active: ready to receive orders')}${check('color','Colour printing')}${check('binding','Binding available')}${check('stationery','Own stationery catalogue and stock')}${check('batch','Scheduled batch delivery available')}<button class="btn loud">Save shop</button></form></section><section><div class="card operation-card"><h2>Staff access</h2><form method="POST" action="/admin/delivery/staff">${field('staffName','Staff name')}${field('email','Email','','email')}<div class="field"><label for="password">Initial password (at least 12 characters)</label><input id="password" name="password" type="password" minlength="12" autocomplete="new-password" required></div><div class="field"><label for="role">Role</label><select id="role" name="role"><option value="partner">Shop partner</option><option value="rider">Delivery rider</option></select></div><button class="btn loud">Create staff account</button></form><p class="field-hint">Partner staff use <a href="/partner/login">partner sign-in</a>. Riders use <a href="/rider/login">rider sign-in</a>.</p></div><h2 class="h-sec">Your shops</h2>${rows || '<div class="empty-state"><h2>Your first local partner.</h2><p>Create a staff account above, then enter and activate the shop. Current orders use the PrintKarr desk.</p></div>'}</section></div>`}));
  });
  app.post('/admin/delivery/staff', ...mutate('admin','/admin/partners',(db,req,res) => {
    const name = String(req.body.staffName || '').trim(), email = String(req.body.email || '').trim().toLowerCase(), password = String(req.body.password || '');
    if (name.length < 2 || name.length > 100 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || email.length > 120 || !['partner','rider'].includes(req.body.role) || password.length < 12 || password.length > 200 || db.users.some(u => u.email.toLowerCase() === email)) throw new Error('Use a unique valid email, staff name and password of 12–200 characters.');
    db.users.push({id:crypto.randomUUID(),role:req.body.role,name,email,passwordHash:hashPassword(password)});
    saveDb(db); res.redirect('/admin/partners');
  }));
  app.post('/admin/partners', ...mutate('admin','/admin/partners',(db,req,res) => { savePartner(db,req.body); saveDb(db); res.redirect('/admin/partners'); }));
  app.get('/admin/delivery', requireRole('admin'), (req,res) => {
    const db = loadDb(), riders = db.users.filter(u => u.role === 'rider');
    const cards = (db.purchases || []).filter(p => p.paymentStatus === 'paid' && !['DELIVERED','CANCELLED','REFUNDED'].includes(p.status)).sort((a,b) => String(a.deliveryStartAt || '').localeCompare(String(b.deliveryStartAt || ''))).map(p => {
      const select = `<label class="operation-label">Fulfilment shop<select name="shopId"><option value="">PrintKarr print desk</option>${(db.partners || []).filter(s=>s.active).map(s=>`<option value="${s.id}" ${p.fulfillmentId === s.id ? 'selected' : ''}>${esc(s.name)}</option>`).join('')}</select></label>`;
      return `<article class="card operation-card"><h2><a href="/admin/purchases/${p.id}">${esc(p.id)}</a></h2><p>${esc(p.address.address)} · ${esc(p.deliveryZone)}</p><p>${esc(p.slot)} · ${esc(p.status)}</p><p>Shop: ${esc(p.fulfillmentName || 'PrintKarr print desk')} · ${esc(p.partnerState || 'Central fulfilment')}${p.partnerSettlement != null ? ' · shop payable ₹' + p.partnerSettlement : ''}</p>${p.partnerRejectReason ? `<p role="alert">${esc(p.partnerRejectReason)}</p>` : ''}${p.status === 'PAID' ? `<form method="POST" action="/admin/delivery/${p.id}/assign">${select}<button class="btn ghost">Assign / reassign shop</button></form>` : ''}${['PAID','READY'].includes(p.status) ? `<form method="POST" action="/admin/delivery/${p.id}/rider"><label class="operation-label">Delivery rider<select name="riderId" required><option value="">Choose rider</option>${riders.map(r=>`<option value="${r.id}" ${p.riderId === r.id ? 'selected' : ''}>${esc(r.name)}</option>`).join('')}</select></label><button class="btn ghost">Assign rider</button></form>` : ''}${p.handedOverAt ? `<p>Handover recorded ${esc(p.handedOverAt)}</p>` : ''}<p>Customer fee stays ₹${p.deliveryFee} after reassignment.</p></article>`;
    }).join('');
    res.send(layout({user:req.user,title:'Delivery batches',active:'/admin/delivery',body:`<div class="page-heading-row"><div class="page-heading"><p class="eyebrow">PICKUP TO YOUR CUSTOMER</p><h1>Delivery <em>batches.</em></h1><p>Assign shops and riders, check handovers and honour every booked delivery window. Central desk capacity is 30 orders per window.</p></div><a class="btn" href="/admin/partners">Manage shops →</a></div><div class="grid c2">${cards || '<div class="empty-state"><h2>Deliveries are up to date.</h2><p>Paid orders awaiting delivery will appear here for shop and rider assignment.</p></div>'}</div>`}));
  });
  app.post('/admin/delivery/:id/assign', ...mutate('admin','/admin/delivery',(db,req,res) => { const p = db.purchases.find(p=>p.id === req.params.id); if(!p)throw new Error('Order not found.'); assignPurchase(db,p,req.body.shopId,req.user.id); saveDb(db); res.redirect('/admin/delivery'); }));
  app.post('/admin/delivery/:id/rider', ...mutate('admin','/admin/delivery',(db,req,res) => { const p=db.purchases.find(p=>p.id===req.params.id); if(!p || !['PAID','READY'].includes(p.status) || !db.users.some(u=>u.id===req.body.riderId && u.role==='rider'))throw new Error('Choose a rider for a paid order.'); p.riderId=req.body.riderId; saveDb(db);res.redirect('/admin/delivery'); }));
  const own = (db,req) => { const shop=(db.partners || []).find(s=>s.staffId===req.user.id); const p=db.purchases.find(p=>p.id===req.params.id && p.fulfillmentId===shop?.id && p.paymentStatus==='paid'); if(!shop || !p)throw new Error('Assigned order not found.');return p; };
  app.get('/partner', requireRole('partner'), (req,res) => {
    const db=loadDb(), shop=(db.partners || []).find(s=>s.staffId===req.user.id);
    const cards = (db.purchases || []).filter(p=>shop && p.fulfillmentId===shop.id && p.paymentStatus==='paid' && !['CANCELLED','REFUNDED','DELIVERED'].includes(p.status)).map(p => `<article class="card operation-card"><h2>${esc(p.id)}</h2><p>${esc(p.slot)} · ${esc(p.status)} · ${esc(p.partnerState || 'ASSIGNED')}</p><p>Shop settlement: ₹${p.partnerSettlement || 0}</p>${p.printIds.map(id=>{const o=db.orders.find(o=>o.id===id);return `<p>${esc(o.document)} · ${esc(printDescription(o))} · ${o.copies} copies · ${esc(o.sides)} · binding: ${esc(o.binding || 'none')} · ${esc(o.status)}<br>Instructions: ${esc(o.notes || 'None')}<br><a href="/partner/files/${encodeURIComponent(o.id)}" target="_blank" rel="noopener">Open assigned document</a></p>`;}).join('')}${p.items.map(i=>`<p>Pack ${i.quantity} × ${esc(i.name)} ${esc(i.color || '')}</p>`).join('')}${p.partnerState === 'ASSIGNED' || !p.partnerState ? button(p.id,'accept','Accept order') + button(p.id,'reject','Reject / ask for reassignment','<label class="operation-label">Reason<input name="reason" required maxlength="200"></label>') : p.partnerState === 'ACCEPTED' ? button(p.id,'ready','Confirm checked & packed') + button(p.id,'problem','Report print / stock problem','<label class="operation-label">Problem<input name="reason" required maxlength="200"></label>') : ''}${p.status==='READY' ? button(p.id,'handover','Hand over to assigned rider','<p>Confirm the rider has collected the whole package.</p>') : ''}</article>`).join('');
    res.send(layout({user:req.user,title:'Shop orders',active:'/partner',body:`<div class="page-heading"><p class="eyebrow">YOUR SHOP’S ORDER DESK</p><h1>${esc(shop?.name || 'Your partner desk')}</h1><p>Accept, prepare and check your assigned orders. Mark complete packages ready, then confirm handover to the assigned rider.</p></div><div class="grid c2">${cards || '<div class="empty-state"><h2>Ready for the next order.</h2><p>Paid orders assigned to your shop will appear here. Keep your catalogue and available stock current.</p><a class="btn" href="/partner/catalogue">Manage stationery →</a></div>'}</div>`}));
  });
  app.get('/partner/files/:id', requireRole('partner'), (req,res) => {
    const db=loadDb(), shop=(db.partners || []).find(s=>s.staffId===req.user.id), o=db.orders.find(o=>shop && o.id===req.params.id && o.fulfillmentId===shop.id && o.paymentStatus==='paid' && ['PRINT_QUEUE','PRINTING','PRINT_FAILED'].includes(o.status));
    if(!o || !db.purchases.some(p=>p.id===o.purchaseId && p.partnerState!=='REJECTED'))return res.sendStatus(404);
    const file=path.resolve(uploadsDir,orderFile(o.id,o.fileExt));if(!file.startsWith(path.resolve(uploadsDir)+path.sep) || !fs.existsSync(file))return res.sendStatus(404);
    res.type(mimeFor(o.fileExt)).sendFile(file);
  });
  app.post('/partner/purchases/:id/accept', ...mutate('partner','/partner',(db,req,res)=>{const p=own(db,req);if(p.status!=='PAID' || p.partnerState && p.partnerState!=='ASSIGNED')throw new Error('Order is no longer waiting for acceptance.');const orders=p.printIds.map(id=>db.orders.find(o=>o.id===id));if(orders.some(o=>o.status!=='PRINT_QUEUE'))throw new Error('Printing has already changed. Contact operations.');for(const o of orders)transition(o,'PRINTING',{by:req.user.id});p.partnerState='ACCEPTED';p.history.push({to:'SHOP_ACCEPTED',by:req.user.id,at:new Date().toISOString()});saveDb(db);res.redirect('/partner');}));
  app.post('/partner/purchases/:id/reject', ...mutate('partner','/partner',(db,req,res)=>{const p=own(db,req),reason=String(req.body.reason||'').trim();if(p.status!=='PAID' || p.partnerState && p.partnerState!=='ASSIGNED' || !reason || reason.length>200)throw new Error('Give a rejection reason before printing starts.');p.partnerState='REJECTED';p.partnerRejectReason=reason;p.history.push({to:'SHOP_REJECTED',by:req.user.id,at:new Date().toISOString(),note:reason});saveDb(db);res.redirect('/partner');}));
  app.post('/partner/purchases/:id/problem', ...mutate('partner','/partner',(db,req,res)=>{
    const p=own(db,req), reason=String(req.body.reason || '').trim();
    if(p.status!=='PAID' || p.partnerState!=='ACCEPTED' || !reason || reason.length>200) throw new Error('Report the problem on an accepted order before handover.');
    for(const id of p.printIds) { const order=db.orders.find(o=>o.id===id); if(order.status==='PRINTING') transition(order,'PRINT_FAILED',{by:req.user.id,note:reason}); }
    p.partnerState='FAILED'; p.partnerRejectReason=reason;
    p.history.push({to:'SHOP_FAILED',by:req.user.id,at:new Date().toISOString(),note:reason});
    saveDb(db); res.redirect('/partner');
  }));
  app.post('/partner/purchases/:id/ready', ...mutate('partner','/partner',(db,req,res)=>{const p=own(db,req);if(p.partnerState!=='ACCEPTED' || p.status!=='PAID')throw new Error('Accept and print the order first.');const orders=p.printIds.map(id=>db.orders.find(o=>o.id===id));if(orders.some(o=>o.status!=='PRINTING'))throw new Error('A print status changed; contact operations.');for(const o of orders){transition(o,'PRINTED',{by:req.user.id,note:'Partner checked physical output'});transition(o,'READY_FOR_PICKUP',{by:req.user.id});}p.status='READY';p.partnerState='READY';p.history.push({to:'READY',by:req.user.id,at:new Date().toISOString()});saveDb(db);for(const o of orders)notifyState(o);res.redirect('/partner');}));
  app.post('/partner/purchases/:id/handover', ...mutate('partner','/partner',(db,req,res)=>{const p=own(db,req);handoverPurchase(db,p,p.riderId,req.user.id);saveDb(db);res.redirect('/partner');}));
  app.get('/rider', requireRole('rider'), (req,res)=>{const db=loadDb();res.send(layout({user:req.user,title:'Delivery trips',active:'/rider',body:`<div class="page-heading"><p class="eyebrow">YOUR NEXT LOCAL DELIVERY</p><h1>Your delivery <em>trips.</em></h1><p>Check the pickup address, collect the complete package and deliver to the customer’s saved map pin.</p></div><div class="grid c2">${(db.purchases || []).filter(p=>p.riderId===req.user.id && ['PAID','READY','OUT_FOR_DELIVERY'].includes(p.status)).map(p=>`<article class="card operation-card"><h2>${esc(p.id)}</h2><p>Pickup: ${esc((db.partners || []).find(s=>s.id===p.fulfillmentId)?.address || db.settings.business.address)}</p><p>Deliver to: ${esc(p.institutionName || '')} ${esc(p.address.address)} · ${esc(p.address.pin)}</p><p>${esc(p.slot)}</p><p>Contact: ${esc(p.address.phone || db.users.find(u=>u.id===p.customerId)?.phone || '')}</p><a href="https://www.google.com/maps?q=${encodeURIComponent(p.address.lat + ',' + p.address.lng)}" class="btn" target="_blank" rel="noopener">Open delivery map →</a><form method="POST" action="/rider/purchases/${p.id}/status"><input type="hidden" name="to" value="${p.status==='OUT_FOR_DELIVERY'?'DELIVERED':'OUT_FOR_DELIVERY'}"><button class="btn loud" ${p.status==='PAID' || p.fulfillmentId && !p.handedOverAt ? 'disabled' : ''}>${p.status==='OUT_FOR_DELIVERY'?'Confirm delivered':'Start delivery →'}</button>${p.fulfillmentId && !p.handedOverAt ? '<p class="field-hint">Waiting for the shop to confirm package handover.</p>' : ''}</form></article>`).join('') || '<div class="empty-state"><h2>No trips waiting.</h2><p>Your assigned pickups and deliveries will appear here. Check with operations if you are expecting a trip.</p></div>'}</div>`}));});
  app.post('/rider/purchases/:id/status', ...mutate('rider','/rider',(db,req,res)=>{const p=db.purchases.find(p=>p.id===req.params.id && p.riderId===req.user.id);if(!p || !(p.status==='READY' && req.body.to==='OUT_FOR_DELIVERY' || p.status==='OUT_FOR_DELIVERY' && req.body.to==='DELIVERED'))throw new Error('Choose the next delivery step for your assigned trip.');if(p.fulfillmentId && !p.handedOverAt)throw new Error('Ask the shop to confirm handover first.');const orders=p.printIds.map(id=>db.orders.find(o=>o.id===id));for(const o of orders){if(req.body.to==='OUT_FOR_DELIVERY'){transition(o,'PICKED_UP',{by:req.user.id});transition(o,'OUT_FOR_DELIVERY',{by:req.user.id});}else{transition(o,'DELIVERED',{by:req.user.id});qualifyForOrder(db,o);}}p.status=req.body.to;p.history.push({to:p.status,by:req.user.id,at:new Date().toISOString()});if(p.status==='OUT_FOR_DELIVERY' && !p.handedOverAt){p.handedOverAt=new Date().toISOString();p.handedOverBy=req.user.id;}saveDb(db);for(const o of orders)notifyState(o);res.redirect('/rider');}));
}
