import { printDescription } from '../public/print-plan.js';
// Public printing flow and marketing pages — PrintKarr print studio.
// No login walls before price. Auth happens once, at OTP time.
import { layout, esc, ASSET_V, THEME_SCRIPTS, icon, pkPublicHeader, pkPublicFooter, DELIVERY_MAP_HEAD, deliveryPicker } from './views.js';
import { uploadStep, optionsStep, bulkPricingGuide } from './views_order.js';
import { campaignDefaults } from './campus.js';
import { PACKS, BOOKING_FEE } from './packs.js';
import { PAGES, seoHead } from './seo.js';

const rs = (n) => '₹' + (Math.round(n * 100) / 100);
const PHONE = '+91 90167 03180';
const EMAIL = 'team@printkarr.in';

const topNav = pkPublicHeader;

function shell({ title, body, desc, active, extraHead, stickyCta, path = active, article = false }) {
  [title, desc] = PAGES[path] || [title, desc];
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)} — PrintKarr</title>
<link rel="icon" href="/favicon.ico?v=${ASSET_V}">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=${ASSET_V}">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=${ASSET_V}">
<link rel="apple-touch-icon" href="/apple-touch-icon.png?v=${ASSET_V}">
<link rel="manifest" href="/site.webmanifest?v=${ASSET_V}">
<meta name="description" content="${esc(desc || "PrintKarr — upload your file, choose your prints and get them delivered to your school, college, home or office. See the full price before payment.")}">
${seoHead(path, title, desc, article)}
<meta name="theme-color" content="#2448EF">
<link rel="preload" href="/fonts/dm-sans-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="/design.css?v=${ASSET_V}">
<link rel="stylesheet" href="/customer.css?v=${ASSET_V}">
<link rel="stylesheet" href="/qk-landing.css?v=${ASSET_V}">
${extraHead || ''}
<link rel="stylesheet" href="/site-overhaul.css?v=${ASSET_V}">
</head>
<body class="public-site"><div class="pk-page">
${topNav(active)}
<a href="#main" style="position:absolute;left:-9999px" onfocus="this.style.left='16px';this.style.top='16px';this.style.zIndex=99;this.style.background='var(--navy)';this.style.color='#fff';this.style.padding='8px 16px';this.style.borderRadius='99px'" onblur="this.style.left='-9999px'">Skip to content</a>
<main id="main">${body}</main>
${stickyCta ? '<div class="sticky-cta"><a href="/order">Upload PDF &amp; Print →</a></div>' : ''}
${pkPublicFooter()}
</div>
<div class="toast" id="toast"></div>
${THEME_SCRIPTS}<script src="/shell.js?v=${ASSET_V}" defer></script>
</body>
</html>`;
}

export { topNav };

export function nearbyShopsPage(partners, area = '') {
  const shops = partners.filter(s => s.active);
  return shell({title:'Nearby print & stationery shops',path:'/shops',extraHead:`<link rel="stylesheet" href="/delivery-service.css?v=${ASSET_V}"><script src="/nearby-shops.js?v=${ASSET_V}" defer></script>`,body:`<section class="service-section service-container shops-page"><p class="eyebrow">YOUR LOCAL PRINT DESK</p><h1>Prints &amp; stationery.<br>From a shop near you.</h1><p>Pick a shop, upload your notes or choose its stationery. School / college scheduled delivery is up to ₹10 and reduces with printed sides; express is ₹25. Home and office delivery is priced by distance in Vapi.</p><form class="shops-search" data-shop-search><div class="field"><label for="shop-search">Find your area or shop</label><input id="shop-search" type="search" value="${esc(area)}" placeholder="Vapi, Sarigam, shop name…" autocomplete="off"></div><button class="btn ghost" type="button" data-locate-shops>Use my location</button></form><p role="status" data-shops-status>Delivery coverage and the full total are checked before payment.</p><div class="nearby-shops" data-shops>${shops.map(s=>`<article class="nearby-shop" data-shop data-lat="${s.lat}" data-lng="${s.lng}" data-search="${esc(s.name+' '+s.address+' '+s.zone)}"><p class="eyebrow">${esc(s.zone)}</p><h2>${esc(s.name)}</h2><p>${esc(s.address)}</p><p class="shop-distance"></p><p class="shop-services">B&amp;W prints${s.color?' · Colour':''}${s.binding?' · Binding':''}${s.stationery?' · Stationery':''}${s.batch?' · Batch delivery':''}</p><div class="hero-actions"><a class="btn loud" href="/order?shop=${encodeURIComponent(s.id)}">Print from here →</a>${s.stationery?`<a class="btn ghost" href="/stationery?shop=${encodeURIComponent(s.id)}">Shop stationery</a>`:''}</div></article>`).join('')}</div><p data-no-shops ${shops.length?'hidden':''}>${shops.length?'No shops match this area. Try another area or order from our print desk.':'We’re onboarding nearby shops. Our PrintKarr print desk can take your order in the meantime.'}</p><a class="rowlink" href="/order">Order from the PrintKarr print desk →</a><aside class="service-note"><h2>One shop, one basket, one delivery.</h2><p>You can combine prints and that shop’s available stationery. Items from different shops need separate orders so stock and delivery stay clear.</p><a class="rowlink" href="/xerox">Own a print or stationery shop? Partner with us →</a></aside></section>`});
}

function reviewsHtml(reviews) {
  const average = reviews.length ? (reviews.reduce((total, r) => total + r.rating, 0) / reviews.length).toFixed(1) : null;
  return `<section class="qk-section qk-container customer-reviews" id="reviews" aria-labelledby="reviews-title" data-reviews>
    <div class="reviews-heading"><div><p class="section-index">CUSTOMER NOTES</p><h2 id="reviews-title">Fresh off<br><em>their print desk.</em></h2><p>Little stories from the people we print for.</p></div>
    <div class="reviews-summary">${average ? `<div><strong>${average}</strong><span>/ 5</span></div><p>${reviews.length} customer ${reviews.length === 1 ? 'review' : 'reviews'}</p>` : '<p>Your experience could be the first.</p>'}<a class="rowlink" href="/customer/profile#review">Leave your review ${icon('arrow-up-right')}</a></div></div>
    ${reviews.length ? `<div class="review-rail" id="review-rail" tabindex="0" role="region" aria-label="Customer review cards. Scroll to read more.">${reviews.map(r => {
      const date = new Date(r.createdAt).toLocaleDateString('en-IN', { day:'numeric', month:'short', year:'numeric', timeZone:'Asia/Kolkata' });
      return `<article class="review-note">
        <div class="review-note-top"><span class="review-stars" role="img" aria-label="${r.rating} out of 5 stars"><span aria-hidden="true">${'★'.repeat(r.rating)}<span class="review-star-empty">${'☆'.repeat(5-r.rating)}</span></span></span><time datetime="${esc(r.createdAt)}">${esc(date)}</time></div>
        <blockquote>${r.text.length > 240 ? `<p>${esc(r.text.slice(0,240))}…</p><details class="review-full"><summary>Read full review</summary><p>${esc(r.text)}</p></details>` : `<p>${esc(r.text)}</p>`}</blockquote>
        <footer class="review-author"><span class="review-avatar" aria-hidden="true">${esc(r.name.charAt(0).toUpperCase())}</span><div><b>${esc(r.name)}</b><small>${r.verified ? `${icon('check')} Printed with us` : 'PrintKarr customer'}</small></div></footer>
        ${r.canDelete ? `<details class="review-delete"><summary>Delete review</summary><p>Remove this review from the home page?</p><form method="POST" action="/reviews/${encodeURIComponent(r.id)}/delete"><button type="submit" class="rowlink">Yes, delete review</button></form></details>` : ''}
      </article>`;
    }).join('')}</div><div class="reviews-navigation" hidden><p>Take a look around.</p><div><button type="button" data-review-direction="-1" aria-controls="review-rail" aria-label="Previous reviews">${icon('arrow-right')}</button><button type="button" data-review-direction="1" aria-controls="review-rail" aria-label="Next reviews">${icon('arrow-right')}</button></div></div>` : '<div class="reviews-empty"><p>No customer notes yet.</p><span>Ordered a print? Tell us how it went in My Account.</span></div>'}
  </section>`;
}

export function landing({ pricing, campaign = campaignDefaults(), walletOffers = [], reviews = [] }) {
  const offers = walletOffers.filter(o => o.enabled !== false && !o.memberDays).slice(0, 3);
  const packs = Object.values(PACKS);
  return shell({ active:'/',title:'Your local print & stationery desk',extraHead:`<link rel="stylesheet" href="/delivery-service.css?v=${ASSET_V}">`,body:`
  <div class="delivery-home">
    <section class="delivery-hero service-container" aria-labelledby="home-title">
      <div class="delivery-hero-copy"><span class="service-tag">${icon('map-pin')} School / college delivery · up to ₹10</span><h1 id="home-title">Your notes. Your essentials.<br><span>At your door.</span></h1><p>Assignments, exam notes, a fresh notebook. Order prints and stationery<br class="desktop-break"> from a nearby shop, and leave the trip to us.</p><div class="hero-actions"><a class="btn loud big" href="/order">Upload &amp; print ${icon('arrow-up-right')}</a><a class="btn ghost big" href="/shops">Find nearby shops ${icon('map-pin')}</a></div><p class="hero-small">PDF, JPG &amp; PNG · B&amp;W ${rs(pricing.bw)} per printed side<br>No sign-in needed to start. Full price before payment.</p></div>
      <div class="delivery-hero-stage"><figure class="delivery-hero-image"><img src="/images/print-desk-hero-v2.webp" width="1122" height="1402" alt="A4 notes and documents ready for printing" fetchpriority="high"><figcaption>YOUR NEXT ASSIGNMENT, SORTED.</figcaption></figure><div class="hero-rate hero-rate-school">${icon('users')}<span>School / college<strong>Up to ₹10 delivery</strong><small>Scheduled · express ₹25</small></span></div><div class="hero-rate hero-rate-local">${icon('map-pin')}<span>Across Vapi<strong>₹15 to ₹50</strong><small>Express, by estimated distance</small></span></div><div class="hero-rate hero-rate-cart">${icon('stack')}<span>Prints + stationery<strong>One delivery.</strong></span></div><div class="hero-rate hero-rate-simple">${icon('check')}<span>Upload. Choose. Relax.<strong>We bring it to you.</strong></span></div></div>
    </section>
    <div class="service-ribbon" aria-label="PrintKarr services"><span>B&amp;W &amp; colour prints</span><span>School &amp; college delivery</span><span>Nearby shops</span><span>Everyday stationery</span></div>
    <section class="service-container service-section" aria-label="Pricing and payment"><p class="service-note">Website orders only · Pay by wallet or Razorpay UPI to save the ₹10 COD fee. Cash on delivery is available; every charge appears before confirmation.</p>${bulkPricingGuide(pricing)}</section>
    <section class="service-container service-section" id="how-it-works"><div class="service-section-heading center"><span class="service-tag">${icon('printer')} How it works</span><h2>A few taps.<br>A little less to do.</h2><p>Get your pages printed without the back-and-forth.</p></div><ol class="service-steps"><li><span class="step-number">STEP 01</span><h3>Upload your file</h3><p>PDF or photo. We count the pages, and you can preview before ordering.</p><div class="step-preview" aria-hidden="true"><div class="step-window-bar">PrintKarr <span>Upload</span></div><div class="sample-upload">${icon('upload-simple')}<b>Drop your notes here</b><small>PDF · JPG · PNG</small></div><div class="sample-file">${icon('file-text')} Assignment.pdf <span>✓</span></div></div></li><li><span class="step-number">STEP 02</span><h3>Make it yours</h3><p>Choose colour, copies and sides. Simple defaults, more options when you need them.</p><div class="step-preview" aria-hidden="true"><div class="step-window-bar">Your print <span>Settings</span></div><p class="sample-label">Print colour</p><div class="sample-options"><b>B&amp;W ✓</b><span>Colour</span></div><p class="sample-label">Paper sides</p><div class="sample-options"><b>Single-sided ✓</b><span>Double-sided</span></div></div></li><li><span class="step-number">STEP 03</span><h3>Choose delivery</h3><p>Enter your address, review the full price and pay. Follow your order all the way to your door.</p><div class="step-preview" aria-hidden="true"><div class="step-window-bar">Delivery <span>Your choice</span></div><div class="sample-delivery">${icon('users')}<span>School / College<small>Scheduled delivery</small></span><b>₹10</b></div><div class="sample-delivery">${icon('map-pin')}<span>Home / Office<small>Vapi express</small></span><b>₹15+</b></div><div class="sample-paid">Clear total. Then payment. ${icon('check')}</div></div></li></ol></section>
    <section class="service-delivery-section" id="delivery"><div class="service-container service-section"><div class="service-section-heading center"><span class="service-tag">${icon('map-pin')} Your place. Your pace.</span><h2>A delivery that<br>fits your day.</h2><p>School, college, home or office. Pick what works for you.</p></div><div class="service-delivery-list"><article class="school-delivery"><div>${icon('users')}<h3>School / College</h3><p>Any school or college in our local coverage. Enter the institution name, address and locality.</p></div><div><strong>₹0–₹10</strong><span>Scheduled delivery</span><small>Need it sooner? Institution express is ₹25.<br>Delivery drops ₹1 per 30 printed sides; free at 300.<br>Earned wallet delivery benefits can reduce it further.</small></div></article><article><div>${icon('map-pin')}<h3>Home / Office / Other</h3><p>Your Vapi address, priced by estimated distance from the shop preparing your order.</p></div><div><strong>₹15 to ₹50</strong><span>Vapi express</span><small>Up to 2 km ₹15 · 2 to 4 km ₹25 · 4 to 6 km ₹35<br>6 to 8 km ₹45 · over 8 km ₹50, within coverage.<br>Daman express ${rs(pricing.delivery.daman ?? 20)}.</small></div></article><article><div>${icon('clock')}<h3>Save with batch delivery</h3><p>Home and office orders share a trip. Choose an available delivery window and save on the charge.</p></div><div><strong>₹10 to ₹25</strong><span>Vapi scheduled delivery</span><small>Free on ₹149+ after discounts.<br>Your booked window is honoured even for a small batch.</small></div></article></div><p class="service-note">Printing is charged separately. Distance is estimated, rather than measured along roads. Confirmed fees, coverage, delivery dates and cutoffs appear before payment. Express and school rates remain separate from the ₹149 offer.</p></div></section>
    <section class="service-container service-section service-benefits"><div class="service-section-heading center"><h2>Less running around.<br><span>More getting things done.</span></h2></div><div class="service-benefits-grid"><article>${icon('file-text')}<h3>Exactly your pages</h3><p>Print a whole document or selected pages. Preview, choose mixed colour pages and keep every copy right.</p></article><article>${icon('stack')}<h3>Everything in one basket</h3><p>A file, a notebook, your notes. Combine that shop’s stationery with prints and pay for one delivery.</p></article><article>${icon('receipt')}<h3>A clear price first</h3><p>Printing, delivery and extras shown before payment. Wallet offers are optional.</p></article><article>${icon('map-pin')}<h3>Your neighbourhood shop</h3><p>Choose an active local partner. They prepare the order; our delivery team brings it to you.</p></article></div></section>
    <section class="service-container service-section service-stationery" id="stationery"><div><span class="service-tag">${icon('stack')} Prints meet stationery</span><h2>A file for your notes.<br><span>A pen for your ideas.</span></h2><p>Notebooks, files and writing essentials from your selected shop. Available stock and selling prices stay visible, so you know what you’re getting.</p><a class="btn loud" href="/stationery">Shop stationery ${icon('arrow-up-right')}</a></div><figure><img src="/images/stationery-demo-hero.png" width="1536" height="1024" alt="Illustrative notebooks, files and writing essentials" loading="lazy"><figcaption>Illustrative collection. Actual products are listed by each shop.</figcaption></figure></section>
    <section class="service-packs-section" id="packs"><div class="service-container service-section"><div class="service-section-heading center"><h2>One semester.<br><span>Plenty of pages.</span></h2><p>Prepaid print bundles for notes, assignments and the next deadline.<br>Book with ₹${BOOKING_FEE}; see your remaining payment in your account.</p></div><div class="service-packs">${packs.map((p,i)=>`<article><span class="pack-label">${esc(p.name)}</span><p>${['For the essentials','For the regulars','For the full semester'][i]}</p><h3>${rs(p.price)}</h3><ul><li>${p.bw} B&amp;W printed sides</li><li>${p.color} included colour sides</li><li>${p.files} paper / cardboard files</li></ul><p class="field-hint">3 unused B&amp;W sides = 1 extra colour side.</p><a class="btn ${i===1?'loud':'ghost'}" href="/customer/packs">View semester packs ${icon('arrow-up-right')}</a></article>`).join('')}</div><p class="service-note center">Use included colour first, then exchange 3 unused B&amp;W sides for each extra colour side.<br>Each copy and printed side counts. Delivery and extras are separate.<br>File handover is arranged with our team.</p></div></section>
    <section class="service-container service-section" id="wallet"><div class="service-section-heading center"><h2>A little ready.<br><span>A little extra.</span></h2><p>Optional wallet offers for your next few orders. Direct payment is also available.</p></div><div class="service-wallet-offers">${offers.map(o=>`<a href="/customer/wallet?offer=${encodeURIComponent(o.id)}"><span>${esc(o.name)}</span><b>Pay ${rs(o.amount)}<br><strong>Get ${rs(o.amount+o.bonus)} balance</strong></b><small>${o.firstOnly?'First eligible top-up only. ':''}${o.freeFiles?`Includes ${o.freeFiles} free files. `:''}${o.freeFirstBatch?'Eligible first school / college batch delivery free. ':''}View offer details ${icon('arrow-up-right')}</small></a>`).join('')}</div><p class="service-note center">Added money has no expiry. Bonus is non-withdrawable and valid for ${campaign.bonusValidityDays} days.<br>Wallet balance and semester pack quota are different benefits.</p></section>
    <section class="service-container service-section service-partners" id="partners"><div><span class="service-tag">${icon('map-pin')} Local shops, connected</span><h2>A shop near you.<br><span>A simpler way to order.</span></h2><p>Find an active print partner, choose its prints and available stationery, and get everything delivered. We’re onboarding shops across selected local areas.</p><a class="btn loud" href="/shops">Find nearby shops ${icon('arrow-up-right')}</a></div><aside class="partner-invite"><div class="partner-icon">${icon('printer')}</div><h3>Run a print or stationery shop?</h3><p>Bring your catalogue online. Prepare assigned orders, hand them to our rider and keep your shop’s work in one place.</p><a class="rowlink" href="/xerox">Become a shop partner ${icon('arrow-up-right')}</a></aside></section>
    <section class="service-container student-banner"><div><h2>The deadline is yours.<br>The delivery is ours.</h2><p>Class notes, project reports and the everyday essentials.<br>School / college delivery up to ₹10 in supported local areas.</p><a class="btn white" href="/order">Upload &amp; print ${icon('arrow-up-right')}</a></div><img src="/images/host-cta.webp" width="1152" height="1728" alt="Student ordering prints from her phone" loading="lazy"></section>
    ${reviewsHtml(reviews)}
    <section class="service-container service-section service-faq" id="faq"><div><h2>A few things<br>before you print.</h2><p>Need a hand? Our team can help.</p><a class="rowlink" href="/contact">Get order help ${icon('arrow-up-right')}</a></div><div><details><summary>Can any school or college order?</summary><p>Yes, within supported local coverage. Enter its full name, address and locality. Scheduled delivery is up to ₹10, reducing with printed sides; institution express is ₹25. Home or hostel orders use address delivery.</p></details><details><summary>How does nearby shop ordering work?</summary><p>Choose an active shop, upload your file or add its available stationery. One shop fulfils each basket. Your receipt shows who is preparing it and its delivery status.</p></details><details><summary>What is batch delivery?</summary><p>Several orders share a scheduled delivery trip. Choose the available date and window before payment. Vapi batch delivery starts at ₹10 and goes up to ₹25 by estimated distance; ₹149+ eligible address baskets have free scheduled delivery.</p></details><details><summary>Do I need a wallet or an app?</summary><p>No app is needed. Start by uploading on the website. Review your price and sign in to pay with the available online method or wallet. Wallet offers are optional.</p></details><details><summary>How are double-sided prints counted?</summary><p>Each printed side is charged. Two pages printed on both sides of one sheet count as two printed sides. Your page selection and copies appear before payment.</p></details><details><summary>What if my print or delivery has a problem?</summary><p>Use order help with your order number. Our team can check the print, arrange a reprint or review the available cancellation and refund options.</p></details><details><summary>When are kiosks coming?</summary><p>Self-service kiosks are in development. Public kiosk ordering, pickup and QR collection are unavailable for now. <a href="/kiosks">View kiosk status</a>.</p></details></div></section>
  </div>`});
}

export function orderPage({ shop, draft, pricing, error, maxMb, surcharges = {}, campaign = campaignDefaults() }) {
  return draft ? optionsStep(null,draft,[],campaign,pricing,surcharges,error) : uploadStep(null,{maxMb,error,shop});
}

export function phonePage({ draft, error, referral }) {
  const s=draft.selections, college=!!s.campusId || !!s.institutionAddress, pickup=s.zone==='pickup', contact=draft.contactForm || draft.contact || {};
  return layout({title:'Confirm & pay',focused:true,back:`/order?draft=${encodeURIComponent(draft.id)}`,extraHead:DELIVERY_MAP_HEAD,body:`
    <h1>Confirm &amp; pay.</h1><section class="order-section"><h2>${esc(draft.document)}</h2><p>${s.effPages} pages · ${esc(printDescription(s))} · ${s.copies} ${s.copies===1?'copy':'copies'}</p><p class="order-contact">${esc(s.institutionName ? s.institutionName+' · '+s.slot : s.campusId ? s.slot : s.area+' · '+s.slot)}</p><a class="order-text" href="/order?draft=${esc(draft.id)}">Edit print or delivery</a></section>
    ${error ? `<p class="login-err" role="alert">${esc(error)}</p>` : ''}
    <form method="POST" action="/order/otp-request" data-inline-order><input type="hidden" name="draft" value="${esc(draft.id)}">
      <section class="order-section"><h2>Your details</h2><div class="field"><label for="nn">Name</label><input id="nn" name="name" value="${esc(contact.name || '')}" autocomplete="name" required maxlength="60"></div><div class="field"><label for="ee">Email</label><input id="ee" name="email" value="${esc(contact.email || '')}" type="email" autocomplete="email" required maxlength="120"></div><div class="field"><label for="pp">Contact phone</label><input id="pp" name="phone" value="${esc(contact.phone || '')}" type="tel" ${pickup ? '' : 'required'} autocomplete="tel" inputmode="tel" maxlength="20"></div>
      ${college || pickup ? '' : `<div class="field"><label for="aa">Street address</label><input id="aa" name="address" value="${esc(contact.address || '')}" required autocomplete="street-address" maxlength="200"></div><div class="grid c2"><div class="field"><label for="pin">PIN code</label><input id="pin" name="pin" value="${esc(contact.pin || '')}" required inputmode="numeric" pattern="[0-9]{6}" autocomplete="postal-code" maxlength="6"></div><div class="field"><label for="ll">Landmark (optional)</label><input id="ll" name="landmark" value="${esc(contact.landmark || '')}" maxlength="100"></div></div>${deliveryPicker(s.area,{...draft.contact?.deliveryPoint,localityId:contact.localityId || draft.contact?.deliveryPoint?.localityId,lat:contact.deliveryLat || draft.contact?.deliveryPoint?.lat,lng:contact.deliveryLng || draft.contact?.deliveryPoint?.lng})}`}
      <input type="hidden" name="referral" value="${esc(contact.referral || referral || '')}"></section>
      <p class="field-hint">We’ll email a code to verify your account before payment.</p><button class="btn loud big" type="submit">Verify email &amp; continue →</button>
    </form>`});
}

export function collectPage({ order, customerName, state, message }) {
  const inner = state === 'ready' && order
    ? `<div class="card rv" style="margin-top:14px">
        <p class="eyebrow">Order #${esc(order.id)} · ${esc(order.document)}</p>
        <p style="font-weight:700;margin:8px 0">${order.pages} pages × ${order.copies} · ${esc(printDescription(order))}</p>
        <p class="muted" style="font-size:13px">Collecting for <b>${esc(customerName || 'the customer')}</b>. Only tap below with the prints in your hand.</p>
        <form method="POST" action="/c/${esc(order.collectToken)}/collect" style="margin-top:14px">
          <button class="btn loud big" type="submit" style="width:100%"><span>I collected my prints ✓</span></button>
        </form></div>`
    : `<div class="card rv" style="margin-top:14px"><p style="font-weight:700">${esc(message || 'This pickup link is no longer valid. Ask the kiosk counter for help.')}</p>
      <p style="margin-top:10px"><a class="rowlink" href="/order">Start a new print →</a></p></div>`;
  return shell({
    active: '/order',
    title: state === 'ready' ? 'Collect your prints' : state === 'collected' ? 'Pickup confirmed' : 'Pickup link',
    body: `
    <section class="pub-wrap" style="max-width:560px">
      <span class="pill rv">Kiosk pickup</span>
      <h1 class="display rv" style="font-size:clamp(2rem,6vw,3.2rem);margin-top:16px">${state === 'ready' ? 'Prints in hand?<br><em>One tap.</em>' : state === 'collected' ? 'Pickup <em>confirmed.</em>' : 'Link <em>expired.</em>'}</h1>
      ${inner}
    </section>`
  });
}

export function otpPage({ draft, email, demoCode, mailError, error }) {
  return layout({title:'Confirm & pay',focused:true,back:`/order/phone?draft=${encodeURIComponent(draft.id)}`,extraHead:DELIVERY_MAP_HEAD,body:`
    <h1>Confirm &amp; pay.</h1><section class="order-section"><h2>Verify your email</h2><p class="order-intro">Enter the 6-digit code sent to ${esc(email)}.</p>${demoCode ? `<p class="login-err">${esc(mailError || 'Email delivery is not configured.')} Demo code: ${esc(demoCode)}</p>` : ''}${error ? `<p class="login-err" role="alert">${esc(error)}</p>` : ''}
      <form method="POST" action="/order/otp-verify" data-inline-order><input type="hidden" name="draft" value="${esc(draft.id)}"><div class="field"><label for="cc">Email code</label><input id="cc" name="code" required inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" autofocus></div><button class="btn loud big" type="submit">Continue to payment →</button></form>
      <form method="POST" action="/order/otp-request" data-inline-order><input type="hidden" name="draft" value="${esc(draft.id)}"><input type="hidden" name="resend" value="1"><button class="order-text" type="submit">Resend code</button></form>
    </section>`});
}

/* ---------- marketing pages (workspace port) ---------- */

function pageWrap(inner) {
  return `<div class="interior-wrap">${inner}</div>`;
}

export function howItWorksPage() {
  return shell({active:'/how-it-works',title:'How it works',body:pageWrap(`<section class="service-guide"><span class="pill">How it works</span><h1 class="display">Your file.<br>Your local print desk.</h1><p>Print notes, assignments and documents, or order stationery from a nearby shop. See the price and delivery window before paying.</p><ol class="guide-steps"><li><h2>Choose a shop or start a print</h2><p><a href="/shops">Find an active nearby shop</a> to choose its prints and stationery. Or start with a file and let us find a suitable fulfilment desk for your location.</p></li><li><h2>Upload and choose your print</h2><p>Upload a PDF, JPG or PNG. Preview your document and choose B&amp;W, colour or mixed pages. Copies and printed sides appear in your total. Optional binding and instructions stay under more options.</p></li><li><h2>Choose where it goes</h2><p>Schools, colleges and classes in local coverage use up to ₹10 scheduled or ₹25 express delivery. Enter the institution’s name and address. Vapi homes and offices use distance-based express or cheaper scheduled delivery. Choose a locality and add the full address so your rider knows where to go.</p></li><li><h2>Review, pay and track</h2><p>See printing, delivery and extras together. You can add that shop’s stationery or another document before paying once. Follow your order from preparation to delivery in your account.</p></li></ol><a class="btn loud" href="/order">Upload &amp; print ${icon('arrow-up-right')}</a><p class="field-hint">Online ordering is available any time. Fulfilment and delivery use the windows shown in checkout. Kiosks are in development.</p></section>`) });
}

export function aboutPage() {
  return shell({
    active: '/about',
    title: 'About PrintKarr',
    body: pageWrap(`<section class="about-story">

      <div class="about-intro"><span class="pill rv">About PrintKarr</span><h1 class="display story-title rv">Paper shouldn’t<br><em>have closing hours.</em></h1>
        <p class="rv">We started in Vapi, Gujarat, because an assignment, admit card, or business document cannot always wait until a shop opens.</p>
        <p class="rv">Today, PrintKarr accepts online orders around the clock for delivery in Vapi and Daman. Upload a PDF, choose your pages, and see the total before paying. Delivery availability and slots are confirmed in checkout; schools and colleges in supported local coverage can use the institution delivery option.</p>
        <p class="rv">We’re connecting local print and stationery shops with online orders and our delivery team. Self-service kiosks are still in development.</p>
        <p class="rv">PrintKarr is operated by PrintKarr Technologies Private Limited. Our service is based in Vapi; delivery coverage does not mean we have a walk-in branch in every city. We show current print prices, delivery fees and available payment options before an order is placed.</p>
        <p class="rv">Customers can sign in with Google to track orders and manage their wallet. Bonus wallet credit is usable on PrintKarr orders and is non-withdrawable; offer eligibility and validity are shown with the offer. Campus batch delivery and address delivery have different availability and fee rules.</p>
        <p class="rv">Read our <a href="/printing-in-vapi">Vapi service guide</a>, <a href="/printing-in-daman">Daman delivery guide</a> and <a href="/printing-prices">printing prices</a>. For coverage or a deadline, contact <a href="tel:+919016703180">+91 90167 03180</a> or <a href="mailto:team@printkarr.in">team@printkarr.in</a>. WhatsApp is optional: the website handles the order flow.</p>
      </div>
      <blockquote class="about-quote rv">If groceries can reach us in minutes, why is printing still stuck behind a shutter at 9 pm? PrintKarr is our answer.<cite>— Anirudh Verma, Founder</cite></blockquote>
      <div class="grid c2"><article class="card rv"><span class="qk-label">Our mission</span><h2>Printing when people need it.</h2><p>Make everyday printing easier with local delivery today and convenient Vapi kiosks after launch.</p></article><article class="card ink rv"><span class="qk-label">Our vision</span><h2>One print network, built with trust.</h2><p>Start with the Vapi pilot and grow a reliable print network for students, families, and businesses.</p></article></div>
    </section>`)
  });
}

export function kioskStatusPage(path = '/kiosks') {
  return shell({ active:path, path, title:'Self-service kiosks · In development', body:pageWrap(`<section class="service-guide"><span class="badge">IN DEVELOPMENT</span><h1 class="display">Self-service kiosks.<br>Coming soon.</h1><p>We’re developing PrintKarr kiosks. Public kiosk ordering, QR collection and pickup are not available yet.</p><p>For now, upload your file online and choose delivery to your school, college, home or office.</p><a class="btn loud big" href="/order">Upload &amp; get prints delivered →</a></section>`) });
}

export function franchisePage() { return kioskStatusPage('/franchise'); }

export function xeroxPage() {
  return shell({active:'/xerox',title:'Become a PrintKarr shop partner',body:pageWrap(`<section class="service-guide"><p class="eyebrow">FOR LOCAL PRINT SHOPS</p><h1 class="display">You print.<br>We bring the orders.</h1><p>Join our network in selected local areas. Customers upload documents and choose settings online. Your shop prepares assigned orders; our rider picks up the package and delivers it.</p><details class="article-toc"><summary>On this page</summary><nav aria-label="Page contents"><a href="#section-1">How partnering works</a><a href="#section-2">What we need from your shop</a><a href="#section-3">Clear settlements</a></nav></details><h2 id="section-1">How partnering works</h2><ol><li>Share your area, equipment and printing capabilities.</li><li>Agree on per-side printing rates and handover responsibilities.</li><li>Accept assigned paid orders in your partner account.</li><li>Print, check every page and mark the package ready.</li><li>Confirm handover to the assigned rider.</li></ol><h2 id="section-2">What we need from your shop</h2><p>A4 printing, reliable staff, a pickup address and agreed operating coverage. Tell us whether you offer colour, binding and stationery. Shops can pause new assignments. Your account shows only assigned customer documents.</p><h2 id="section-3">Clear settlements</h2><p>Agreed B&amp;W and colour rates are recorded per printed side. Shop payable amounts are shown on assigned orders. PrintKarr coordinates delivery; commercial terms, reprints and settlement timing are agreed during onboarding.</p><a class="btn loud big" href="/contact">Apply to become a partner →</a><p><a href="/partner/login">Already onboarded? Partner sign-in →</a></p></section>`)});
}

export function contactPage({ sent } = {}) {
  return shell({
    active: '/contact',
    title: 'Contact PrintKarr',
    body: pageWrap(`<div style="display:grid;gap:32px" class="contact-grid"><div>
      <span class="pill rv">Contact</span>
      <h1 class="display rv" style="font-size:clamp(2rem,5vw,3rem);margin-top:16px">A little help.<br><em>Right when you need it.</em></h1>
      <ul class="rv" style="margin-top:24px;list-style:none;display:flex;flex-direction:column;gap:16px;font-size:14px">
        <li>${icon('phone')} <a href="tel:+919016703180">${PHONE}</a> · <a href="https://wa.me/919016703180">WhatsApp</a><br><span class="muted">Online orders any time. Confirm delivery availability and slots in checkout.</span></li>
        <li>${icon('envelope')} <a class="rowlink" href="mailto:${EMAIL}">${EMAIL}</a></li>
        <li>${icon('map-pin')} PrintKarr Technologies Private Limited<br><span class="muted">Based in Vapi, Gujarat. Delivery across Vapi and Daman; selected colleges in Sarigam and Bhilad. Kiosk locations will be announced after launch.</span></li>
      </ul></div>
      <form class="card rv" method="POST" action="/contact">
        ${sent ? `<p class="pill" style="margin-bottom:12px">✓ Received. We’ll get back to you.</p>` : ''}
        <div class="field"><label for="field-model">How can we help?</label><select id="field-model" name="model" required><option value="" disabled selected>Choose one</option><option>Help with my print order</option><option>School / college delivery</option><option>Need a custom solution</option><option>Onboard my Xerox shop</option><option>Home / office delivery</option><option>Just saying hello</option></select></div>
        <div class="grid c2"><div class="field"><label for="field-name">Name</label><input id="field-name" name="name" required></div><div class="field"><label for="field-phone">Phone</label><input id="field-phone" name="phone" type="tel" autocomplete="tel" required></div></div>
        <div class="field"><label for="field-email">Email</label><input id="field-email" name="email" type="email" required></div>
        <div class="field"><label for="field-message">Message</label><textarea id="field-message" name="message" rows="4"></textarea></div>
        <button class="btn loud" style="width:100%" type="submit"><span>Send enquiry →</span></button>
      </form></div>
      <style>.contact-grid{grid-template-columns:1fr}@media(min-width:768px){.contact-grid{grid-template-columns:.9fr 1.1fr}}</style>`)
  });
}

export const POSTS = [
  {
    slug: 'prepare-documents-for-printing-vapi', title: 'How to prepare a PDF for printing in Vapi', modified: '2026-10-01',
    excerpt: 'Check PDF pages, margins, colour and delivery details before paying for assignments, resumes or everyday documents.',
    headings: ['Start with the final document', 'Check every page in the PDF', 'Match the page range to the file', 'Keep page size and margins deliberate', 'Choose colour and sides for the purpose', 'Review copies and the complete price', 'Choose delivery before your deadline', 'Inspect the finished print'],
    sources: [{ title: 'Adobe: adjusting PDF page size for printing', url: 'https://helpx.adobe.com/acrobat/desktop/print-documents/set-up-and-print-pdfs/page-size.html' }, { title: 'Adobe: printing PDFs in Acrobat Reader', url: 'https://helpx.adobe.com/reader/desktop/print-pdfs.html' }],
    body: [
      'Finish edits in the original document before exporting your PDF. Check names, roll numbers, dates, page headings and any information the recipient expects. A readable filename such as assignment-final.pdf helps you recognise the correct version at upload. Use the original document where possible rather than a screenshot of text; a screenshot may already contain blurred letters or missing edges.',
      'Open the exported PDF on the device you will use to order. Scroll through the cover, contents, diagrams, references and final page rather than checking only the first screen. Look for missing characters, shifted tables, accidental blank pages and images that have become hard to read. If something is wrong, correct the original document and export again before uploading.',
      'PDF page positions and the page numbers printed inside a report can differ. A cover may be the first page in the file even when the report starts numbering later. For example, a cover followed by ten numbered pages contains eleven PDF pages. Use the upload preview and detected page count to identify your selection, then check that the final selected range includes everything required.',
      'Choose the paper size required by your college, employer or document issuer. Check whether the PDF mixes portrait and landscape pages or different sizes. Adobe distinguishes fitting content to a printable area from printing at actual size; either choice can change the result. If exact scale matters, such as for a template, confirm that requirement with support before paying rather than assuming automatic fitting will preserve it.',
      'Black-and-white is often sufficient for ordinary text. Choose colour when a diagram, annotation or instruction depends on colours being distinguishable. Read the recipient’s rules before selecting single-sided or double-sided printing. A submission that requires single-sided pages should follow that rule even if duplex would use less paper. For a report read as a booklet, also check the intended page order.',
      'Review the number of copies separately from the page selection. Selecting ten pages and two copies requests twenty printed pages, while the number of physical sheets depends on the sides setting. Check the current printing charge and every delivery or applicable fee in the order summary. Wallet bonus terms and eligibility can differ from the amount you pay into your wallet, so read the displayed offer details.',
      'PrintKarr accepts online orders at any time, with delivery options depending on the location and available service. Vapi and Daman delivery and selected-campus batch slots are different arrangements. Enter your destination and choose an available option before checking out. If an assignment deadline is close, confirm that the promised timing works for you; online availability does not promise immediate physical delivery.',
      'After receiving the prints, compare the first and last pages, page order, copies, colour choice and legibility with your PDF. Keep your order reference and contact support promptly if the result differs from the selected settings. Retain your own original file for future corrections; PrintKarr’s print-file retention process is separate from your personal copy. The preparation checklist is useful even when you print elsewhere.'
    ]
  },
  {
    slug: 'admit-card-printing-checklist', title: 'Admit card printing: a checklist before exam day', modified: '2026-10-01',
    excerpt: 'Use the issuing authority’s instructions to check your admit card, print settings and deadline before ordering.',
    headings: ['Read the current official instructions', 'Download and verify the correct file', 'Check photographs and machine-readable codes', 'Choose the required print settings', 'Keep every required page', 'Leave time for delivery and inspection', 'Compare the print with the original', 'Pack the documents the authority asks for'],
    body: [
      'Start with the exam authority’s official website, admit card and current instructions for your specific examination. There is no universal rule requiring all admit cards to be colour, black-and-white, single-sided or accompanied by the same identity document. Follow the issuer’s stated requirements. If a coaching message or social post conflicts with the official instructions, ask the authority to resolve the difference before ordering.',
      'Download the admit card yourself from the official source and keep the original PDF available. Check that it belongs to the correct examination and session, and review your name, application details, examination centre and reporting information. A printing service cannot correct the authority’s record. If those details appear wrong, use the issuer’s support process rather than editing the admit card to make it look correct.',
      'Preview every page at a readable zoom. The photograph, signature area, barcode or QR code should not be obscured by cropping, annotations or a screenshot interface. A blurred download cannot be repaired simply by printing in colour. When something appears incomplete, download again from the official source or ask the issuing authority for guidance. Avoid redrawing codes or adding unrequested information.',
      'Select the paper size, colour and sides specified for the exam. If the instructions require an A4 colour single-sided print, choose those settings explicitly. Where the issuer does not specify a setting, choose a legible result and contact the authority if unsure about acceptance. Do not assume a document preview on a bright screen guarantees that a faint photograph or tiny text will print clearly.',
      'Check the complete file before choosing a page range. Some admit cards include instructions, declarations or additional pages that must be brought to the centre. A cover or instruction page can also change the PDF page positions. Select all required pages and the required number of copies; do not remove a page merely because it looks unrelated to the first-page admission details.',
      'Work backwards from the time you need to leave for the examination, including time to receive and inspect the print. PrintKarr accepts online orders at any time, but the available delivery options depend on your address and selected service. A participating campus morning slot is not automatically an urgent home-delivery service. Confirm timing with support before paying if the available option does not clearly meet your deadline.',
      'When the prints arrive, compare them with the saved PDF. Check your details, all page edges, photographs, codes, instructions and page order. If the job does not match your selected settings or text is unreadable, keep the order reference and contact support promptly. Leave enough time for a correction rather than discovering the issue while travelling to the centre.',
      'Read the authority’s checklist again when packing your bag. Bring only the photographs, original identity documents, declarations or other materials it requires, and complete signatures only where and when instructed. Keep digital backups for your own reference, but do not treat a phone copy as a substitute where a physical document is required. A PrintKarr print does not establish document validity or guarantee examination admission.'
    ]
  },
  {
    slug: 'running-a-printkarr-kiosk', title: 'PrintKarr kiosk planning: costs and responsibilities', modified: '2026-10-01',
    excerpt: 'Compare hardware, consumables, servicing and partnership responsibilities before requesting a kiosk proposal.',
    headings: ['Treat this as a proposed partnership', 'Separate hardware from operating costs', 'Choose a capacity for actual demand', 'List the recurring costs', 'Decide who owns each responsibility', 'Plan access, uptime and exceptions', 'Model demand without assuming returns', 'Ask for a location-specific proposal'],
    body: [
      'PrintKarr’s first self-service kiosk is planned for Vapi. This guide is a preparation checklist for a proposed kiosk partnership, not an operating-profit report from a live public installation. Delivery ordering is available separately. Before committing to a machine or a location, ask the team about pilot availability, the intended deployment process and which terms will apply to your proposal.',
      'The public partnership page lists indicative hardware reference prices of ₹1,29,000 plus GST for PrintKarr PRO and ₹69,000 plus GST for PrintKarr MINI. Those figures should not be read as an all-inclusive installation or operating quote. Ask what is included, what is optional, how taxes apply and whether delivery, setup, connectivity or other location requirements add costs.',
      'The published capacity references are 1,950 sheets for PRO and 650 sheets for MINI. Paper capacity is not the same as daily print throughput, guaranteed uptime or colour capability. Estimate the likely mix of short assignments and longer documents at your location, then ask which proposed hardware configuration fits it. Consider how often somebody could realistically refill paper during busy periods.',
      'Make a recurring-cost list before building a budget: paper, toner or ink, consumable replacements, electricity, internet connectivity, cleaning, servicing and any space cost. Actual amounts depend on equipment, suppliers, usage and the agreement. Obtain quotations rather than copying generic rent, electricity or commission numbers. Also ask how damaged sheets, unsuccessful jobs and unexpected component replacements are accounted for.',
      'PrintKarr describes franchise-owned, space-partner and custom partnership models. The public overview gives different responsibilities for hardware, space, consumables, support and the platform. Turn that overview into a written checklist for your own agreement. Identify who purchases refills, receives service alerts, attends the location, approves refunds and communicates with users when the machine cannot fulfil an order.',
      'Check power, network reliability, access permissions and physical placement with the building owner. A machine in a college corridor cannot serve users when that corridor is locked. Discuss accessible placement, safe cable routing and the response when internet, power or printing fails. Ask for the proposed service arrangement and escalation contacts instead of assuming that self-service means nobody needs to manage it.',
      'Estimate demand from a real location survey or existing print activity, using quieter days as well as deadline peaks. Separate projected paid orders from free or promotional printing. Compare expected revenue against consumables and the quoted agreement terms, and include a lower-demand scenario. A kiosk price or paper capacity does not establish a payback period, fixed income or guaranteed return.',
      'Use the partnership enquiry with your city, type of location, expected audience, available space, power and internet details. Ask for current pricing, deployment readiness, servicing terms, payment responsibilities and contract conditions in writing. Keep your investment decision tied to that proposal. Until a public kiosk launch and pickup location are announced, customer orders should use the available delivery service rather than travel to an assumed kiosk.'
    ]
  },
  {
    slug: 'replacing-xerox-queues', title: 'Online printing or a Xerox shop: how to choose', modified: '2026-10-01',
    excerpt: 'Compare document uploads, print settings, delivery and in-person services before choosing how to print.',
    headings: ['Start with the job you need done', 'Use online printing for a prepared document', 'Choose an in-person service when it helps', 'Compare the complete job price', 'Make the print settings explicit', 'Allow for delivery and collection time', 'Handle personal documents carefully', 'Know what PrintKarr offers today'],
    body: [
      'A prepared PDF and a damaged paper original are different printing jobs. Before choosing a provider, decide whether you need ordinary document printing, photocopying, scanning, binding, lamination or a specialist finish. An online document upload does not automatically offer every service associated with a Xerox shop. Checking this first prevents an order that cannot produce the result you actually need.',
      'Online ordering can be useful when the final file is already on your phone or computer. You can select pages, copies, colour and available sides, then review the summary before payment. It is especially helpful for repeatable document jobs such as assignments, resumes or forms. You still need to check the document carefully; a digital order will not correct spelling, missing pages or inaccurate information.',
      'An in-person shop may be the better fit if you need someone to inspect a physical original, discuss a binding finish or check paper options that an online flow does not list. Confirm the shop’s actual services and opening hours rather than assuming every counter has the same equipment. For a specialist requirement, ask for a sample or clear description of the intended result before committing to the whole job.',
      'Compare the complete job rather than only the advertised price per page. Page selection, copies, colour and sides can change the printing amount. Delivery, other applicable fees or a separate finishing service can change the total. A wallet bonus is order credit under displayed rules, not cash returned to you. Read any offer eligibility or expiry before treating it as a saving for your particular job.',
      'Make the instructions precise whichever provider you use. Identify pages by their positions in the PDF, check whether the recipient requires single-sided printing, and explain when colour is essential for a diagram. Confirm the number of copies separately. A short review of these details is easier than fixing a whole assignment that was printed in the wrong range or orientation.',
      'For delivery, select an option that reaches the correct address or participating campus within your deadline. For a shop visit, include travel, opening hours and collection arrangements. Online order placement at night does not guarantee that physical printing or delivery happens immediately. If the timing is urgent or unclear, confirm it with the provider before paying instead of relying on a broad availability slogan.',
      'Check your file for unrelated personal information before sharing it with any provider. Use the intended upload process, keep your own original and read the provider’s privacy information. If a document needs a signature or correction after printing, follow the recipient’s instructions. No general printing service can establish that an identity document, certificate or submitted form is legally valid.',
      'PrintKarr currently offers online document ordering and available delivery in Vapi and Daman, with selected-campus arrangements in Sarigam and Bhilad. Its first Vapi self-service kiosk is planned; there is no announced public pickup address. Start with the delivery options shown for your destination. If you need binding, lamination, walk-in collection or an unlisted specialist service, confirm availability with support rather than assuming the planned kiosk provides it today.'
    ]
  },
  {
    slug: 'colleges-24-7-print', title: 'Campus printing: delivery slots and kiosk planning', modified: '2026-10-01',
    excerpt: 'Plan student document delivery and evaluate a proposed campus kiosk without confusing ordering hours with access or delivery.',
    headings: ['Separate current delivery from a planned kiosk', 'Check whether your campus participates', 'Understand the slot and cutoff', 'Review fees and wallet conditions', 'Give complete handover information', 'Prepare files for the institution’s rules', 'Evaluate a kiosk with the campus team', 'Define responsibilities before a partnership'],
    body: [
      'Students often need printing around assignment and examination deadlines, but a useful service needs clear delivery arrangements as well as online ordering. PrintKarr accepts online document orders at any time. Selected-campus batch delivery is a current order option where enabled. Self-service kiosk deployment is a separate planned initiative, beginning with a Vapi pilot; it should not be described as an open machine at every college.',
      'Check the participating campuses and options shown in the order flow. General mentions of Sarigam or Bhilad do not mean every college or hostel in those areas is covered. If your campus is absent, ask support about your exact location before paying for a service that may not reach it. Do not choose another campus merely to obtain a slot or a delivery offer.',
      'Read the available delivery slot and the order cutoff together. A morning slot may require placing the order before an overnight cutoff; an afternoon option can have a different deadline. Use the current times shown for your chosen campus rather than an old promotion or a screenshot. Missing a cutoff can change the available slot, so check the order summary immediately before you confirm payment.',
      'Review printing charges, delivery fees and offer conditions separately. Free batch delivery can depend on eligibility or a minimum order, while express delivery remains a paid option when available. The first-wallet offer and other top-ups may add bonus credit under displayed rules. Bonus credit is non-withdrawable and may expire; a wallet purchase does not automatically entitle every order to free campus delivery.',
      'Provide a working contact number and select the correct campus delivery point. Keep track of the promised slot and follow the order status in your account. If the displayed point is unsuitable for your class timetable or hostel access, confirm another arrangement with support before checkout. A late-delivery wallet credit applies only under an enabled eligible guarantee and does not replace planning around a submission deadline.',
      'Check the assignment or examination instructions before uploading. Confirm the required pages, copies, colour, sides and any cover sheet with the institution’s rules. Export and inspect the final PDF rather than sending several unfinished versions. For a group assignment, decide who will receive the prints and verify the complete page range so a teammate’s section is not accidentally left out.',
      'A campus considering a kiosk should first identify the intended users, permitted access hours, expected demand and proposed location. Assess power, internet connectivity, safe placement, accessibility and how users will get help. A machine behind a locked building door cannot provide unrestricted access. Ask PrintKarr about the planned pilot and a location-specific proposal instead of assuming installation is immediately available.',
      'The public partnership overview offers franchise-owned, space-partner and custom models. Before agreeing, document who provides the space, hardware, consumables, maintenance access and student support. Ask how failed jobs, payments, refunds and service interruptions would be handled. Use the campus partnership enquiry for a proposal. Until a launch and pickup location are announced, students should select the actual delivery option offered for their campus.'
    ]
  },
];

export function blogsPage() {
  return shell({active:'/blogs',title:'Printing guides',body:pageWrap(`<div class="information-hero"><p class="eyebrow">NOTES FROM THE PRINT DESK</p><h1 class="display">Good prints begin<br><em>with a little know-how.</em></h1><p>Practical guides for assignments, admit cards and documents. A few checks now can save a reprint later.</p></div><div class="journal-grid">${POSTS.map((p,i)=>`<a class="journal-card" href="/blogs/${esc(p.slug)}"><span class="eyebrow">PRINTING GUIDE · ${String(i+1).padStart(2,'0')}</span><h2>${esc(p.title)}</h2><p>${esc(p.excerpt)}</p><span class="rowlink">Read guide ${icon('arrow-up-right')}</span></a>`).join('')}</div>`)});
}

export function blogArticlePage(slug) {
  const post = POSTS.find((p) => p.slug === slug);
  if (!post) return shell({ title: 'Not found', body: pageWrap(`<h1 class="display">Story not found</h1><a class="rowlink" href="/blogs">Back to blogs</a>`) });
  return shell({
    path: '/blogs/' + post.slug,
    article: post,
    desc: post.excerpt,
    title: post.title,
    body: pageWrap(`<article class="service-guide"><nav class="guide-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/blogs">Printing guides</a></nav><h1 class="display">${esc(post.title)}</h1><p class="muted">${esc(post.excerpt)}</p><p class="guide-byline">By <a href="/about">PrintKarr</a> · Reviewed <time datetime="${esc(post.modified)}">1 October 2026</time></p><details class="article-toc"><summary>In this guide</summary><nav aria-label="Article contents">${post.headings.map((heading,i)=>`<a href="#section-${i+1}">${esc(heading)}</a>`).join('')}</nav></details>${post.body.map((p, i) => `<section class="article-section" id="section-${i+1}"><h2>${esc(post.headings[i])}</h2><p>${esc(p)}</p></section>`).join('')}${post.sources ? `<section><h2>Further reading</h2><ul>${post.sources.map(s => `<li><a href="${esc(s.url)}">${esc(s.title)}</a></li>`).join('')}</ul></section>` : ''}<aside class="guide-next"><h2>Put your document into print.</h2><p>Check <a href="/printing-prices">current print prices</a>, <a href="/printing-in-vapi">Vapi delivery</a> or <a href="/printing-in-daman">Daman delivery</a>. For a deadline or campus address, <a href="/contact">confirm coverage and timing</a> before paying.</p><a class="btn loud" href="/order">Upload &amp; print ${icon('arrow-up-right')}</a></aside></article>`)
  });
}

export function termsPage() {
  return shell({
    path: '/terms',
    title: 'Terms & Conditions',
    body: pageWrap(`<article class="service-guide"><h1 class="display">Terms &amp; Conditions</h1><p>PrintKarr online document printing is operated by PrintKarr Technologies Private Limited, based in Vapi. Self-service kiosks are planned; no public kiosk pickup address has been announced.</p><details class="article-toc"><summary>On this page</summary><nav aria-label="Page contents"><a href="#section-1">Print jobs and delivery</a><a href="#section-2">Files and account access</a><a href="#section-3">Payments, wallet and refunds</a><a href="#section-4">Contact</a></nav></details><h2 id="section-1">Print jobs and delivery</h2><p>You confirm you have the right to print the file you upload. Review your PDF, page range, copies, colour, sides and delivery details before placing the order. Online ordering is available any time; delivery availability and slots are shown in checkout. For a time-sensitive document or college address, confirm arrangements before paying.</p><h2 id="section-2">Files and account access</h2><p>Uploaded files are stored to process your order and supplied to the authorized print workflow. Eligible order files are removed after delivered, refunded or cancelled status and the configured retention period. Keep your original document; PrintKarr is not a permanent file archive. Read our <a href="/privacy">privacy information</a>.</p><h2 id="section-3">Payments, wallet and refunds</h2><p>Pay online or with your wallet, or choose cash with the extra cash-handling fee shown before confirmation. Review printing, delivery and processing fees in the final quote. Wallet bonus credit is non-withdrawable and usable only on PrintKarr orders; offer eligibility and expiry rules apply. Hardware failures and order issues should be reported to support for review and the appropriate refund process.</p><h2 id="section-4">Contact</h2><p>For an order issue, quote your order number to <a href="mailto:${EMAIL}">${EMAIL}</a> or <a href="tel:+919016703180">+91 90167 03180</a>.</p></article>`)
  });
}

export function privacyPage() {
  return shell({
    path: '/privacy',
    title: 'Privacy Policy',
    body: pageWrap(`<article class="service-guide"><h1 class="display">Privacy Policy</h1><p>PrintKarr Technologies Private Limited uses uploaded documents, account and contact details, delivery information and payment references to process print orders, provide support and maintain order and wallet records.</p><details class="article-toc"><summary>On this page</summary><nav aria-label="Page contents"><a href="#section-1">Documents</a><a href="#section-2">Accounts, payments and cookies</a><a href="#section-3">Your requests</a></nav></details><h2 id="section-1">Documents</h2><p>Uploads are sent over HTTPS on the live website. Files are stored on the service and made available to the authorized order and print workflow. Eligible order files are removed after delivered, refunded or cancelled status and the configured retention period, during a scheduled cleanup. Removal is not immediate when printing finishes. Keep your original file; abandoned drafts and unassigned uploads are removed after 24 hours during cleanup. Active or failed orders are kept for processing or correction. This cleanup covers our working storage; copies already downloaded by a customer or shop and provider backups follow their own retention.</p><h2 id="section-2">Accounts, payments and cookies</h2><p>Google sign-in identifies your customer account. Session cookies keep you signed in. Contact and delivery details support the order, while order history, payment references and wallet transactions are retained independently of uploaded files. Online card or UPI payment entry is handled by the available payment provider; PrintKarr uses payment references to confirm orders.</p><h2 id="section-3">Your requests</h2><p>For questions about information or a deletion request, contact <a href="mailto:${EMAIL}">${EMAIL}</a>. Include your account email or order number so the team can identify the relevant records; avoid attaching sensitive documents to the request. We review requests alongside order support and records that need to be retained.</p></article>`)
  });
}

export function vapiPage() {
  return shell({ path: '/printing-in-vapi', body: pageWrap(`
    <article class="service-guide">
      <nav class="guide-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><span>Printing in Vapi</span></nav>
      <p class="eyebrow">PRINTKARR · LOCAL DOCUMENT PRINTING</p>
      <h1 class="display">A4 printing in Vapi.<br><em>For your next deadline.</em></h1>
      <p>PrintKarr prints A4 college assignments, project reports, forms and everyday documents for local delivery in Vapi. Upload a PDF, JPG or PNG from your phone, choose B&amp;W or colour, and review the printing and delivery total before payment.</p>
      <div class="local-print-actions"><a class="btn loud" href="/order">Upload &amp; print →</a><a class="rowlink" href="https://wa.me/919016703180">WhatsApp 9016703180</a></div>
      <details class="article-toc"><summary>On this page</summary><nav aria-label="Page contents"><a href="#section-1">What can you print?</a><a href="#section-2">Delivery areas and timing</a><a href="#section-3">How much does printing cost?</a><a href="#section-4">Are PrintKarr kiosks open in Vapi?</a><a href="#section-5">How do I order?</a><a href="#section-6">How do I print a college assignment in Vapi?</a><a href="#section-7">How do I set my school or college address?</a><a href="#section-8">Can I get it before my submission deadline?</a><a href="#section-9">Wallet payment and file access</a><a href="#section-10">Before you print</a><a href="#section-11">Need help with a local order?</a></nav></details><h2 id="section-1">What can you print?</h2>
      <p>Order black-and-white or colour document prints for college assignments, project reports, resumes, office documents, forms, tickets and admit cards. Select your page range and copies in the order flow. Follow your college, employer or exam authority’s requirements for paper and print settings.</p>
      <h2 id="section-2">Delivery areas and timing</h2>
      <ul><li><strong>Vapi:</strong> local delivery to the address you select, subject to checkout coverage.</li><li><strong>Daman:</strong> see our <a href="/printing-in-daman">Daman document delivery guide</a> for address and timing checks.</li><li><strong>Schools and colleges:</strong> choose institution delivery, then enter the name, address and locality. Local coverage is checked before payment.</li></ul>
      <p>Online ordering is available 24/7. Delivery uses available slots and service rules, rather than an immediate-delivery promise. Enter the correct address, PIN code and locality, then review the fee and slot. For a deadline or an address the checkout cannot accept, call <a href="tel:+919016703180">+91 90167 03180</a> before paying.</p>
      <h2 id="section-3">How much does printing cost?</h2>
      <p>See our <a href="/printing-prices">current A4 printing rates</a>. Your exact total depends on selected pages, copies, colour, sides and delivery. The quote shows printing, delivery and applicable fees before payment. <a href="/order">Upload your document to see your quote</a>; a displayed per-page rate is not an all-inclusive delivery charge.</p>
      <h2 id="section-4">Are PrintKarr kiosks open in Vapi?</h2>
      <p>Our first kiosk is planned in Vapi. No public kiosk pickup address has been announced yet. Please use delivery or <a href="/contact">contact us for launch updates</a>. Service coverage is not a direction to a walk-in store; do not travel to an assumed kiosk location.</p>
      <h2 id="section-5">How do I order?</h2>
      <ol><li>Upload your document and check its page count.</li><li>Select the pages, copies and print settings you need.</li><li>Select your delivery address or eligible campus slot and review the total.</li><li>Use your wallet or the available payment options, then place the order and follow it in your customer account.</li></ol>
      <h2 id="section-6">How do I print a college assignment in Vapi?</h2>
      <p>Upload your assignment and check the preview before paying. Choose the pages, single-sided or both sides, and copies your college requires. For a report with colour diagrams, use mixed B&amp;W and colour printing to select the colour pages individually. A Vapi hostel or home uses address delivery; choose school / college delivery only when the institution is your actual destination.</p>
      <p lang="hi">वापी में कॉलेज असाइनमेंट या A4 प्रिंटआउट चाहिए? PDF या फोटो अपलोड करें। भुगतान से पहले प्रिंट सेटिंग, डिलीवरी शुल्क और समय देखें।</p>
      <h2 id="section-7">How do I set my school or college address?</h2>
      <p>School / college scheduled delivery is up to ₹10 and decreases with printed sides; institution express is ₹25. Enter the institution name, address and locality. Vapi address express costs ₹15 to ₹50 by estimated distance; scheduled delivery costs ₹10 to ₹25. Daman uses its current checkout rate.</p>
      <h2 id="section-8">Can I get it before my submission deadline?</h2>
      <p>Check the next available delivery window shown in your order. Campus and scheduled routes use cutoff times; uploading after a cutoff moves the window to the next day. Online ordering is available at any time, but printing or delivery is not guaranteed around the clock. For a deadline outside the displayed window, <a href="/contact">confirm with support</a> before paying.</p>
      <h2 id="section-9">Wallet payment and file access</h2>
      <p>Google sign-in gives access to your order history and wallet. Purchased balance and promotional bonus credit can have different rules; bonus credit is non-withdrawable and usable on PrintKarr orders. Review the current offer and its validity before a top-up. You can complete an order on the website without a mandatory WhatsApp conversation.</p>
      <p>Keep the final PDF until you have checked the delivered print. Uploaded order files are removed after eligible completed, refunded or cancelled orders pass the configured retention period; the website is not a document archive. Read the <a href="/privacy">file-handling information</a> before uploading sensitive material.</p>
      <h2 id="section-10">Before you print</h2>
      <p>Check fonts, margins, cover pages and diagrams in the final PDF. Read our <a href="/blogs/prepare-documents-for-printing-vapi">document preparation guide</a> and <a href="/blogs/admit-card-printing-checklist">admit card checklist</a>.</p>
      <h2 id="section-11">Need help with a local order?</h2>
      <p><a href="tel:+919016703180">Call 9016703180</a>, <a href="https://wa.me/919016703180">message us on WhatsApp</a> or <a href="/contact">contact PrintKarr</a> to confirm college coverage, urgent delivery timing or kiosk partnership enquiries.</p>
    </article>`) });
}

export function damanPage() {
  return shell({ path:'/printing-in-daman', body:pageWrap(`<article class="service-guide">
    <nav class="guide-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><span>Printing in Daman</span></nav>
    <p class="eyebrow">PRINTKARR · DAMAN DOCUMENT DELIVERY</p><h1 class="display">Printing in Daman.<br><em>Start from your phone.</em></h1>
    <p>PrintKarr offers online document printing with local delivery in Daman. The service is based in Vapi: upload your PDF or photo, choose black-and-white or colour printing, and confirm a Daman delivery address and available slot before paying.</p>
    <div class="local-print-actions"><a class="btn loud" href="/order">Upload &amp; print ${icon('arrow-up-right')}</a><a class="rowlink" href="/printing-prices">See printing prices</a></div>
    <details class="article-toc"><summary>On this page</summary><nav aria-label="Page contents"><a href="#section-1">Confirm your Daman address first</a><a href="#section-2">Documents for work, applications and everyday use</a><a href="#section-3">Can I order at night?</a><a href="#section-4">Daman delivery and college batches are different</a><a href="#section-5">What does the order cost?</a><a href="#section-6">Is there a Daman shop or pickup kiosk?</a><a href="#section-7">Before submitting and after delivery</a></nav></details><h2 id="section-1">Confirm your Daman address first</h2><p>Enter a complete address, recipient contact number and PIN code, and check the map point when the order flow asks for it. These details help distinguish your destination from the service’s Vapi base. Review the available delivery option and its fee before placing the order. If checkout does not accept your location, contact <a href="tel:+919016703180">+91 90167 03180</a> before making a payment; a city-wide description does not confirm every individual address.</p>
    <h2 id="section-2">Documents for work, applications and everyday use</h2><p>Use the service for PDFs, resumes, forms, tickets, assignments, reports and admit cards. Select only the PDF pages you need and the correct number of copies. For diagrams or photographs that must retain colour, choose colour explicitly. Check the organisation’s instructions before selecting paper size, single-sided or double-sided output. A printed copy does not replace an original document when an application requires the original.</p>
    <h2 id="section-3">Can I order at night?</h2><p>Yes, online orders can be placed at any time. The delivery time depends on the available slot, location and order rules. We do not promise an immediate or overnight delivery simply because the website accepts an order. For an exam, travel departure or appointment, confirm the timing before payment and allow time to inspect the delivered pages.</p>
    <h2 id="section-4">Daman delivery and college batches are different</h2><p>A residential or business delivery in Daman is not automatically a campus batch. Fixed college slots and free-delivery offers apply only where the college and order qualify. Selected colleges in Sarigam and Bhilad require separate confirmation; availability there does not establish a Daman campus partnership. Choose the option that matches the actual destination rather than selecting a college to obtain a delivery benefit.</p>
    <h2 id="section-5">What does the order cost?</h2><p>Our <a href="/printing-prices">printing price guide</a> shows current per-page rates. Selected pages, copies, print settings, delivery and applicable fees determine the final total. Preview the quote before using wallet balance or the available online payment options. Promotional wallet credit is non-withdrawable and can have eligibility and expiry rules; review them before topping up.</p>
    <h2 id="section-6">Is there a Daman shop or pickup kiosk?</h2><p>No public Daman pickup address has been announced. PrintKarr’s first self-service kiosk is planned for Vapi, so this page describes delivery rather than directions to a Daman branch. Use <a href="/printing-in-vapi">the Vapi guide</a> for the current kiosk status and service-base information.</p>
    <h2 id="section-7">Before submitting and after delivery</h2><p>Open the final PDF, check every page and leave important text away from page edges. Use the <a href="/blogs/prepare-documents-for-printing-vapi">PDF preparation checklist</a> and <a href="/blogs/admit-card-printing-checklist">admit card guide</a> when relevant. Keep your original file and compare the delivery with your order settings. If you need help, quote the order number when you <a href="/contact">contact PrintKarr</a>. WhatsApp is optional; uploading, payment and order placement happen on the website.</p>
  </article>`) });
}

export function printPricesPage({ pricing }) {
  return shell({ path:'/printing-prices', body:pageWrap(`<article class="service-guide pricing-guide">
    <nav class="guide-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><span>Printing prices</span></nav>
    <p class="eyebrow">A4 DOCUMENT PRINTING · VAPI &amp; DAMAN</p><h1 class="display">Clear prices.<br><em>Before you pay.</em></h1><p>These are PrintKarr’s current A4 document printing rates. The final quote includes your selected pages, copies and settings, plus delivery and applicable fees. Review that quote before placing an order.</p>
    <div class="local-print-actions"><a class="btn loud" href="/order">Get your exact quote ${icon('arrow-up-right')}</a></div>
    <div class="grid c3 guide-rates">${[['Black & white',pricing.bw],['Colour',pricing.color],['Student B&W',pricing.studentBw]].map(([label,value])=>`<section class="card"><details class="article-toc"><summary>On this page</summary><nav aria-label="Page contents"><a href="#section-1">${label}</a><a href="#section-2">Pages, sheets and copies</a><a href="#section-3">Black-and-white, colour and student rates</a><a href="#section-4">Delivery is quoted separately</a><a href="#section-5">Wallet credit and offers</a><a href="#section-6">A quote tailored to your document</a></nav></details><h2 id="section-1">${label}</h2><strong>${rs(value)}</strong><p>per printed page${label==='Student B&W' ? ', when eligible' : ''}</p></section>`).join('')}</div>
    ${bulkPricingGuide(pricing)}<h2 id="section-2">Pages, sheets and copies</h2><p>A PDF page and a physical sheet are different. A double-sided sheet can carry two printed document pages; it does not automatically halve the charge for the document content. Selecting ten document pages and two copies produces twenty printed pages. Review the detected page count, selected range and copies so you do not pay to print unwanted covers or blank pages.</p>
    <h2 id="section-3">Black-and-white, colour and student rates</h2><p>Use black-and-white for text-only documents when colour is not required. Select colour for diagrams, photographs or instructions that depend on it. Student pricing applies only when the account or order meets the eligibility shown by the service; it is not a blanket discount on every colour or delivery charge. Choose single-sided or double-sided printing according to your college, employer or exam authority’s requirements.</p>
    <h2 id="section-4">Delivery is quoted separately</h2><p>Per-page rates describe printing. Address delivery in <a href="/printing-in-vapi">Vapi</a> or <a href="/printing-in-daman">Daman</a>, eligible campus batches and express options can have different fees and availability. Free campus delivery, minimum order rules and cutoff times apply only where the checkout confirms eligibility. Enter the actual destination and inspect the full total; do not assume that a wallet bonus covers every delivery option.</p>
    <h2 id="section-5">Wallet credit and offers</h2><p>Your wallet can pay for PrintKarr orders. Current top-up offers and their bonus amounts appear on the <a href="/customer/wallet">wallet page</a>. Purchased balance and promotional credit have different rules: bonus credit is non-withdrawable, usable on PrintKarr orders and subject to any offer expiry. Membership passes, when enabled, are separate from ordinary top-ups. Review the terms shown for the specific offer before paying.</p>
    <h2 id="section-6">A quote tailored to your document</h2><p>Upload the final file, choose page ranges and copies, select print settings and delivery, then review the itemised quote. It shows the price for that order rather than an estimate for an unseen document. There is no mandatory WhatsApp step. Follow our <a href="/how-it-works">order guide</a> or <a href="/contact">contact support</a> if the destination or a time-sensitive request needs clarification.</p>
  </article>`) });
}
