import assert from 'node:assert/strict';
import fs from 'node:fs';
import express from 'express';
import {rateLimit} from 'express-rate-limit';
import {runInNewContext} from 'node:vm';
import {request} from 'node:http';
import {contactPage,contactThankYouPage,CONTACT_TOPICS,notFoundPage,landing,POSTS} from '../lib/views_public.js';
import {parseCookies} from '../lib/auth.js';
import {blankDb} from '../lib/db.js';
import {SITE,discoveryRoutes,purchaseAnalytics} from '../lib/seo.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'file:///C:/Users/WELCOME/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const source=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8').replaceAll('\r\n','\n');
const app=express();app.use(express.urlencoded({extended:false}));app.use(express.static('public',{index:false}));discoveryRoutes(app,POSTS);
let failure=false,saves=0,db={leads:[]};
const siteOrigin=runInNewContext(source.match(/function siteOrigin\(req, res, next\) \{[^]*?\n\}/)[0]+'\nsiteOrigin;',{SITE,URL});
runInNewContext(source.slice(source.indexOf('const contactLimiter ='),source.indexOf("app.get('/blogs',")),{app,rateLimit,siteOrigin,parseCookies,contactPage,contactThankYouPage,CONTACT_TOPICS,loadDb:()=>structuredClone(db),saveDb:next=>{if(failure)throw Error('disk failure');db=next;saves++;}});
const paid={id:'test-receipt',total:28,status:'PAID',paymentStatus:'paid'};
app.get('/privacy-check',(_req,res)=>res.send(landing({pricing:blankDb().pricing}).replace('</main>',purchaseAnalytics(paid)+'<span data-contact-confirmed hidden></span></main>')));
app.get('/customer/orders/private-file-name',(_req,res)=>res.send(landing({pricing:blankDb().pricing}).replace(/<link rel="canonical"[^>]*>/,'').replace('<title>','<title>Private document.pdf ')));
app.use((_req,res)=>res.status(404).send(notFoundPage()));
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({channel:'msedge',headless:true});const priorId=process.env.GA4_MEASUREMENT_ID;
try {
  const missing=await fetch(base+'/missing-page');assert.equal(missing.status,404);assert.ok((await missing.text()).includes('Back to Home'));
  const body={model:CONTACT_TOPICS[0],name:'Test Person',phone:'9000000000',email:'test@example.com',message:'A test enquiry',website:''};
  const send=(fields,headers={})=>fetch(base+'/contact',{method:'POST',body:new URLSearchParams(fields),headers,redirect:'manual'});
  assert.equal((await send(body,{origin:'https://evil.example'})).status,403);assert.equal(saves,0);
  failure=true;let result=await send(body);assert.equal(result.status,503);assert.equal(result.headers.get('set-cookie'),null);assert.ok((await result.text()).includes('A test enquiry'));assert.equal(saves,0);
  failure=false;result=await send({...body,at:'fake',role:'admin'},{origin:'https://www.printkarr.in'});assert.equal(result.status,303);assert.equal(saves,1);assert.equal(db.leads[0].role,undefined);assert.notEqual(db.leads[0].at,'fake');
  result=await send({...body,message:'<script>alert(1)</script>',email:'bad'});assert.equal(result.status,400);assert.ok((await result.text()).includes('&lt;script&gt;'));
  for(const order of [{...paid,paymentStatus:'pending'},{...paid,paymentStatus:'cod_pending'},{...paid,status:'REFUNDED'},{...paid,preview:true}])assert.equal(purchaseAnalytics(order),'');
  const escaped=purchaseAnalytics({...paid,id:'receipt</script>'});assert.ok(!escaped.includes('receipt</script>'));assert.equal(JSON.parse(escaped.match(/>(.*)<\/script>/)[1]).transaction_id,'receipt</script>');
  const redirect=await new Promise((resolve,reject)=>{const req=request(base+'/contact?source=test',{method:'POST',headers:{host:new URL(SITE).host}},res=>{res.resume();resolve({status:res.statusCode,location:res.headers.location});});req.on('error',reject);req.end('name=kept');});assert.equal(redirect.status,308);assert.equal(redirect.location,SITE+'/contact?source=test');
  delete process.env.GA4_MEASUREMENT_ID;
  let page=await browser.newPage();await page.goto(base+'/privacy-check');assert.equal(await page.locator('#cookie-dialog').count(),0);assert.equal(await page.locator('script[src*="googletagmanager"]').count(),0);await page.close();
  process.env.GA4_MEASUREMENT_ID='G-LOCALTEST1';
  const context=await browser.newContext();let googleRequests=0;
  await context.route(/google-analytics|googletagmanager/,route=>{googleRequests++;return route.fulfill({status:200,contentType:'text/javascript',body:'/* Local consent test. No Google connection. */'});});
  page=await context.newPage();await page.goto(base+'/privacy-check');await page.locator('#cookie-dialog[open]').waitFor();assert.equal(googleRequests,0);
  await page.getByRole('button',{name:'Essential only'}).click();await page.reload();assert.equal(googleRequests,0);assert.equal(await page.locator('#cookie-dialog[open]').count(),0);
  await page.getByRole('button',{name:'Cookie preferences'}).click();await page.getByRole('button',{name:'Allow analytics'}).click();await page.waitForFunction(()=>!!window.dataLayer);assert.equal(googleRequests,1);
  let events=await page.evaluate(()=>dataLayer.map(args=>Array.from(args)));assert.ok(events.some(x=>x[0]==='event'&&x[1]==='page_view'));assert.ok(events.some(x=>x[1]==='generate_lead'));assert.ok(events.some(x=>x[1]==='purchase'));
  await page.reload();events=await page.evaluate(()=>dataLayer.map(args=>Array.from(args)));assert.ok(!events.some(x=>x[1]==='purchase'),'Receipt refresh does not duplicate purchase');
  await page.goto(base+'/customer/orders/private-file-name?email=secret@example.com');events=await page.evaluate(()=>dataLayer.map(args=>Array.from(args)));assert.ok(!/private-file-name|Private document|secret@example/.test(JSON.stringify(events)),'Analytics redacts route identifiers, title and queries');
  await page.getByRole('button',{name:'Cookie preferences'}).click();const count=googleRequests;await Promise.all([page.waitForNavigation(),page.getByRole('button',{name:'Essential only'}).click()]);assert.equal(googleRequests,count,'Withdrawal stops new Google loads');
  await context.close();
  console.log('Checklist checks passed: failed writes, bounded contact fields, origin aliases/rejection, escaped errors, real 404, HTTPS POST upgrade, disabled GA4, opt-in/rejection/withdrawal, safe event metadata, and paid-only deduplicated purchase events.');
}finally{if(priorId===undefined)delete process.env.GA4_MEASUREMENT_ID;else process.env.GA4_MEASUREMENT_ID=priorId;await browser.close();await new Promise(r=>server.close(r));}
